### ISSUE TITLE
Refactor to redux-toolkit

### ISSUE THREAD

**Issue by asherccohen** [daslaf/react-clean-architecture#1]
This is a great repo and article, very well explained. 
We need more of these examples around.
One thing I suggest is to modernize the redux implementation with the new redux-toolkit and rtk-query.

It would make for a more interesting and up-to-date read.

Happy to review if you're willing to take the idea onboard.

**Comment by daslaf** [comment]
Hey @asherccohen 

Yes of course, what I was initially planning was having different implementations of `CounterStore` using different libraries. If you want to contribute, feel free to submit a PR. 😄
