### ISSUE TITLE
Extend example with payload actions

### ISSUE THREAD

**Issue by decamel** [daslaf/react-clean-architecture#2]
First of all, this architecture example is a good point to start from. Thank you for your effort.

Could you please extend this repository with payload use cases?
For example it could contain theme switching example. It would be enough to understand how to work with it.

**Comment by daslaf** [comment]
Hi @dessy4oko!

Thanks for commenting. What other types of use cases do you think it would be useful to implement?

**Comment by decamel** [comment]
Hi @daslaf!

I think that every new React/Redux coder wants to know how to work and manage with basic data structures like `Array`, `Map`, `Graph`. Also it would be useful to create a basic example for user management (authentication, profile) because most of times states like that are complex enough. I know that there are thousands of articles and they could just google for it, but when you are a newbie you don't even know what keywords to use for.

**Comment by daslaf** [comment]
That sounds like a good idea, but out of scope for this particular repo. What I'm probably going to do is to create a dummy e-commerce app or something like that using CLEAN architecture on a different repo. I'll let you know when that is finished (It will probably take a while though)
